### ISSUE TITLE
can't  find file "stop_value=Stopping_U_multi_fidelity(search_x,kriging_model_lf,kriging_model_discrepancy)"

### ISSUE THREAD

**Issue by Summersyz** [JiaxiangYi96/AMK-MCS-AEFF#1]
can't  find file "stop_value=Stopping_U_multi_fidelity(search_x,kriging_model_lf,kriging_model_discrepancy)"

**Comment by JiaxiangYi96** [comment]
Hey, 

sorry for the later reply, the file "Stopping_U_multi_fidelity.m" is been uploaded

Best
